name: typed_fb_data
description: Date interface for typed firebase
version: 0.2.0
homepage: https://github.com/kdy1/typed_fb_data

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  built_value_generator: ^8.0.2
  build_runner: ^1.7.3
