name: typed_fb_data
description: Date interface for typed firebase
version: 0.0.1
homepage: https://github.com/kdy1/typed_fb_data

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ^7.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  built_value_generator: ^7.0.8
  build_runner: ^1.7.3
